### ISSUE TITLE
accessing commit that changed oca csv urls

### ISSUE THREAD

**Issue by nmontalbanocouncil** [nycdb/nycdb#272]
I apologize if this is the wrong space to raise this question or if I'm missing something, but I tried updating my nycdb package after the recent [commit](https://github.com/nycdb/nycdb/commit/e4a59b3acf6629fefb0d18be74e6a5a44343eb43) that was made to change the oca csv urls but it did not update anything on my local computer. Does `nycdb-0.2.8` not include these changes? I also tried to install using the most recent commit directly but it did not work 
`python3 -m pip install "nycdb@git+https://github.com/nycdb/nycdb.git@e4a59b3acf6629fefb0d18be74e6a5a44343eb43"`

I'm wondering if the package on [PyPI](https://pypi.org/project/nycdb/) needs to be updated or if there is another way I can access the changes. 

Thank you so much for the help!

**Comment by austensen** [comment]
Hey @nmontalbanocouncil , yes unfortunately we haven't updated the package on PyPi recently. @aepyornis Do you know how that's done? Maybe we can work on getting something set up to automate those updates?

For now though, you should be able to clone this repo and install locally. I think the issue you're having with that install command is that the python package is in the `/src` directory - so you'd need to point to there rather than the root of the project.

**Comment by nmontalbanocouncil** [comment]
Thank you for the help! Everything is working after I cloned the repo and installed locally. I will look out for any future updates!
