### ISSUE TITLE
Pull Request #274

### ISSUE THREAD

**Issue by wvasquezz** [nycdb/nycdb#283]
In reference to pull request 274, thanks for getting back to me and making the changes to pluto_latest yaml file. How can I gain access to these changes? Unfortunately, when I attempt to load the pluto_latest data onto my postgres client, the 2020 census columns are still missing. I uninstalled and reinstalled nycdb and the issue still persists.

**Comment by austensen** [comment]
Are you installing it using `pip install nycdb`? 
Unfortunately we are behind on updating nycdb on pypi, so it doesn't have those latest changes. Since it will take us a little while to fix that, for now you'll need to install it another way. 
You can clone this repository, go into the `/src` folder, and then run `pip install .` to install it locally. Then anytime there are more changes made, you can use git to pull the latest changes and then reinstall it that way.

**Comment by aepyornis** [comment]
I also just updated the version on pypi, so if you reinstall nycdb again from pypi you should get the latest version.

**Comment by wvasquezz** [comment]
It works! Thank you very much.
