### ISSUE TITLE
some "DRIVE" addresses get changed to "DRIVEIVE" and "PLAINS" to "PLACEAINS"

### ISSUE THREAD

**Issue by sraby** [nycdb/nycdb#75]
> select streetname from hpd_registrations where streetname ~ 'DRIVEIVE';

Looks like it's an issue with src/nycdb/address.py

**Comment by toolness** [comment]
I think this might be happening because perhaps the original open data had certain abbreviations in it like "RIVERSIDE DR", which the original code in `src/nycdb/address.py` was probably trying to un-abbreviate to `RIVERSIDE DRIVE`.  However, I'm guessing that at some point the open data stopped using those abbreviations, but the find/replace algorithm still saw the "DR" in "DRIVE" and changed it to "RIVERSIDE DRIVEIVE".  Just a hunch though!

In any case, this would be a great bug to fix because it shows up in some user-facing products that use NYCDB, like [WoW's page for 11 Riverside Drive](https://whoownswhat.justfix.nyc/address/MANHATTAN/11/RIVERSIDE%20DRIVE):

> ![image](https://user-images.githubusercontent.com/124687/65167215-1f3e0180-da10-11e9-84b7-7e4c0fb75eb1.png)

Also, I'm not sure if there are actually still some street names that use the "DR" abbreviation... It would be good to check to see if that's the case in the open data feed, so that we still convert those to "DRIVE", while ensuring that we don't convert any occurrences of "DRIVE" to "DRIVEIVE".
